version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.${CUSTOM_HOSTNAME}'
    container_name: gitlab
    env_file:
      - .env
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.${CUSTOM_HOSTNAME}'
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        gitlab_rails['time_zone'] = 'Europe/Berlin'
        gitlab_rails['gitlab_default_theme'] = 2
        gitlab_rails['usage_ping_enabled'] = false
        prometheus['enable'] = false
        # gitlab_rails['gitlab_shell_ssh_port'] = 2222

    shm_size: '256m'
    ports:
      #  - '80:80'
      #  - '443:443'
      - '2222:22'
    volumes:
      - './gitlab_data/config:/etc/gitlab'
      - './gitlab_data/logs:/var/log/gitlab'
      - './gitlab_data/data:/var/opt/gitlab'
    networks:
      - traefik_ext
      - gitlab_network
    labels:
      # Enable Traefik
      - "traefik.enable=true"
      # Set Network to use
      - "traefik.docker.network=traefik_ext"
      # Enable gzip compression
      - "traefik.http.middlewares.gzip.compress=true"
      # Load dynamic config
      - "traefik.http.routers.gitlab.middlewares=secHeaders@file,gzip"

      - "traefik.http.routers.gitlab.entrypoints=websecure"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.${CUSTOM_HOSTNAME}`)"
      - "traefik.http.routers.gitlab.tls.certresolver=le_http_challenge"
      - "traefik.http.routers.gitlab.tls=true"
      - "traefik.http.routers.gitlab.service=gitlab"

      - "traefik.http.services.gitlab.loadbalancer.server.port=80"

      - "traefik.http.routers.gitlab.middlewares=gitlab-headers"
      - "traefik.http.middlewares.gitlab-headers.headers.customrequestheaders.X_FORWARDED_PROTO=https"
      - "traefik.http.middlewares.gitlab-headers.headers.customrequestheaders.X_Forwarded-Ssl=on"
      - "traefik.http.middlewares.gitlab-headers.headers.customresponseheaders.X_FORWARDED_PROTO=https"
      - "traefik.http.middlewares.gitlab-headers.headers.customresponseheaders.X_Forwarded-Ssl=on"

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    environment:
      - TZ='Europe/Berlin'
      - FF_NETWORK_PER_BUILD=true
    volumes:
      - ./runner_data/config/:/etc/gitlab-runner:Z
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab_network
    labels:
      - traefik.enable=false

networks:
  traefik_ext:
    external: true
  gitlab_network:
    external: false
